"""Tests for APCR telemetry in simulate_hierarchical_controller.py.

These tests verify that:
1. APCR telemetry fields are initialized in telemetry template
2. APCR telemetry fields are appended from sagittal_diag
3. APCR1b profile exists with correct settings
4. APCR diagnostics keys are generated by controller
5. APCR does not change WBC path
"""

import pytest


class TestAPCR1bProfile:
    """Test suite for APCR1b profile configuration."""

    def test_apcr1b_profile_exists_and_is_opt_in_only(self):
        """Test that APCR1b profile exists and is opt-in only (not in baseline)."""
        from wheeled_biped.controllers.sagittal_velocity_damped_balance_controller import (
            SagittalAuthoritySchedule,
        )

        # APCR1b should be opt-in only (not the default)
        apcr1b = SagittalAuthoritySchedule(
            profile_name="APCR1b_test",
            applies_to_variants=("low_0p300",),
            enable_active_pitch_crossing=True,
            active_pitch_crossing_recovery_gate_mode=True,
            apc_inner_exit_m=0.07,
            apc_outer_enter_m=0.10,
            apc_opposite_overshoot_m=0.00,
        )

        # Verify profile has correct APCR settings
        assert apcr1b.enable_active_pitch_crossing is True
        assert apcr1b.active_pitch_crossing_recovery_gate_mode is True
        assert apcr1b.apc_inner_exit_m == 0.07
        assert apcr1b.apc_outer_enter_m == 0.10
        assert apcr1b.apc_opposite_overshoot_m == 0.00

    def test_apcr1b_in_sagittal_authority_profiles_dict(self):
        """Test that APCR1b profile is defined in SAGITTAL_AUTHORITY_PROFILES."""
        from scripts.simulate_hierarchical_controller import SAGITTAL_AUTHORITY_PROFILES

        # Verify APCR1b profile exists
        assert "APCR1b_active_pitch_crossing_early_release" in SAGITTAL_AUTHORITY_PROFILES, (
            "APCR1b profile not found in SAGITTAL_AUTHORITY_PROFILES"
        )

        apcr1b = SAGITTAL_AUTHORITY_PROFILES["APCR1b_active_pitch_crossing_early_release"]

        # Verify APCR1b has correct settings
        assert apcr1b.enable_active_pitch_crossing is True
        assert apcr1b.active_pitch_crossing_recovery_gate_mode is True
        assert apcr1b.apc_inner_exit_m == 0.07, (
            f"Expected inner_exit_m=0.07, got {apcr1b.apc_inner_exit_m}"
        )
        assert apcr1b.apc_outer_enter_m == 0.10, (
            f"Expected outer_enter_m=0.10, got {apcr1b.apc_outer_enter_m}"
        )
        assert apcr1b.apc_opposite_overshoot_m == 0.00, (
            f"Expected opposite_overshoot_m=0.00, got {apcr1b.apc_opposite_overshoot_m}"
        )


class TestAPCRControllerDiagnostics:
    """Test suite for APCR diagnostics generated by controller."""

    def test_apcr_diagnostics_keys_generated(self):
        """Test that controller generates all expected APCR diagnostic keys."""
        from wheeled_biped.controllers.sagittal_velocity_damped_balance_controller import (
            SagittalVelocityDampedBalanceController,
            SagittalAuthoritySchedule,
        )

        # Create controller with APCR enabled
        schedule = SagittalAuthoritySchedule(
            profile_name="test_apcr",
            applies_to_variants=("low_0p300",),
            enable_active_pitch_crossing=True,
            active_pitch_crossing_recovery_gate_mode=True,
            apc_inner_exit_m=0.07,
            apc_outer_enter_m=0.10,
            apc_opposite_overshoot_m=0.00,
        )

        controller = SagittalVelocityDampedBalanceController(
            authority_schedule=schedule,
        )

        # Call compute with correct signature
        tau, diagnostics = controller.compute(
            pitch_x_rad=0.05,
            pitch_rate_x_rad_s=0.0,
            sagittal_velocity_m_s=0.0,
            wheel_vel_left_rad_s=0.0,
            wheel_vel_right_rad_s=0.0,
            sagittal_position_error_m=0.0,
            com_z_m=0.35,
            roll_y_rad=0.0,
            contact_valid=True,
            height_variant_name="low_0p300",
        )

        # Verify expected APCR diagnostic keys exist
        expected_keys = [
            "active_pitch_crossing_enabled",
            "active_pitch_crossing_state",
            "active_pitch_crossing_active",
            "active_pitch_crossing_inner_exit_m",
            "active_pitch_crossing_outer_enter_m",
            "active_pitch_crossing_recovery_gate_mode",
            "final_wheel_tau_with_apc",
            "final_wheel_tau_without_apc",
        ]

        for key in expected_keys:
            assert key in diagnostics, f"Expected APCR diagnostic key '{key}' not found"

        # Verify APCR is enabled
        assert diagnostics["active_pitch_crossing_enabled"] is True

        # Verify recovery gate mode is enabled
        assert diagnostics["active_pitch_crossing_recovery_gate_mode"] is True

        # Verify threshold values are correct
        assert diagnostics["active_pitch_crossing_inner_exit_m"] == 0.07
        assert diagnostics["active_pitch_crossing_outer_enter_m"] == 0.10


class TestAPCRDefaultValues:
    """Test suite for APCR default values when disabled."""

    def test_apcr_disabled_has_safe_defaults(self):
        """Test that APCR fields have safe defaults when controller is disabled."""
        from wheeled_biped.controllers.sagittal_velocity_damped_balance_controller import (
            SagittalVelocityDampedBalanceController,
            SagittalAuthoritySchedule,
        )

        # Create controller WITHOUT APCR (default)
        schedule = SagittalAuthoritySchedule(
            profile_name="test_no_apcr",
            applies_to_variants=("low_0p300",),
            enable_active_pitch_crossing=False,
        )

        controller = SagittalVelocityDampedBalanceController(
            authority_schedule=schedule,
        )

        # Call compute with correct signature
        tau, diagnostics = controller.compute(
            pitch_x_rad=0.0,
            pitch_rate_x_rad_s=0.0,
            sagittal_velocity_m_s=0.0,
            wheel_vel_left_rad_s=0.0,
            wheel_vel_right_rad_s=0.0,
            sagittal_position_error_m=0.0,
            com_z_m=0.35,
            roll_y_rad=0.0,
            contact_valid=True,
            height_variant_name="low_0p300",
        )

        # When APCR is disabled, these should be False or have safe defaults
        assert diagnostics["active_pitch_crossing_enabled"] is False
        assert diagnostics["active_pitch_crossing_active"] is False
        assert diagnostics["active_pitch_crossing_state"] == "NEUTRAL"


class TestAPCRTelemetrySourceInspection:
    """Test suite for APCR telemetry plumbing via source inspection."""

    def test_apcr_telemetry_initialization_in_simulator(self):
        """Test that APCR telemetry fields are initialized in simulate_hierarchical_controller.py."""
        import ast
        import pathlib

        # Read the simulator source file
        simulator_path = pathlib.Path("f:/ROBOTCUATAO/Wheeled-bipedal-robot-simulation/scripts/simulate_hierarchical_controller.py")
        source = simulator_path.read_text()

        # Parse the source into an AST
        tree = ast.parse(source)

        # Look for telemetry initialization that includes active_pitch_crossing fields
        apcr_fields_found = []
        for node in ast.walk(tree):
            if isinstance(node, ast.Dict):
                # Look for keys that look like telemetry field initialization
                for key in node.keys:
                    if isinstance(key, ast.Constant) and isinstance(key.value, str):
                        if "active_pitch_crossing" in key.value:
                            apcr_fields_found.append(key.value)

        # Verify key APCR fields are initialized
        critical_apcr_fields = [
            "active_pitch_crossing_enabled",
            "active_pitch_crossing_state",
            "active_pitch_crossing_active",
        ]

        for field in critical_apcr_fields:
            assert field in apcr_fields_found, (
                f"APCR telemetry field '{field}' not found in telemetry initialization"
            )

    def test_apcr_telemetry_appending_in_simulator(self):
        """Test that APCR telemetry fields are appended in simulate_hierarchical_controller.py."""
        import pathlib

        # Read the simulator source file
        simulator_path = pathlib.Path("f:/ROBOTCUATAO/Wheeled-bipedal-robot-simulation/scripts/simulate_hierarchical_controller.py")
        source = simulator_path.read_text()

        # Verify APCR telemetry appending
        key_apcr_appends = [
            'telemetry["active_pitch_crossing_enabled"].append',
            'telemetry["active_pitch_crossing_state"].append',
            'telemetry["active_pitch_crossing_active"].append',
            'telemetry["active_pitch_crossing_inner_exit_m"].append',
            'telemetry["active_pitch_crossing_outer_enter_m"].append',
        ]

        for append_pattern in key_apcr_appends:
            assert append_pattern in source, (
                f"APCR telemetry append pattern '{append_pattern}' not found in simulator source"
            )


class TestAPCR1mTelemetryPlumbing:
    """Test suite for APCR1m telemetry plumbing."""

    def test_apcr1m_telemetry_initialization_in_simulator(self):
        """Test that APCR1m telemetry fields are initialized in simulate_hierarchical_controller.py."""
        import pathlib

        # Read the simulator source file
        simulator_path = pathlib.Path("f:/ROBOTCUATAO/Wheeled-bipedal-robot-simulation/scripts/simulate_hierarchical_controller.py")
        source = simulator_path.read_text()

        # Verify APCR1m fields are initialized
        apcr1m_fields = [
            "apcr1m_pitch_blend_active",
            "apcr1m_pitch_blend_scale",
            "apcr1m_pitch_blend_block_reason",
            "apcr1m_tau_pitch_before_blend",
            "apcr1m_tau_pitch_after_blend",
            "apcr1m_startup_guard_active",
            "apcr1m_recenter_active",
            "apcr1m_pitch_safe",
            "apcr1m_height_safe",
            "apcr1m_contact_safe",
            "apcr1m_roll_safe",
            "apcr1m_pitch_rate_safe",
        ]

        for field in apcr1m_fields:
            assert f'"{field}": []' in source, (
                f"APCR1m telemetry field '{field}' not found in telemetry initialization"
            )

    def test_apcr1m_telemetry_appending_in_simulator(self):
        """Test that APCR1m telemetry fields are appended in simulate_hierarchical_controller.py."""
        import pathlib

        # Read the simulator source file
        simulator_path = pathlib.Path("f:/ROBOTCUATAO/Wheeled-bipedal-robot-simulation/scripts/simulate_hierarchical_controller.py")
        source = simulator_path.read_text()

        # Verify APCR1m telemetry appending
        key_apcr1m_appends = [
            'telemetry["apcr1m_pitch_blend_active"].append',
            'telemetry["apcr1m_pitch_blend_scale"].append',
            'telemetry["apcr1m_pitch_blend_block_reason"].append',
            'telemetry["apcr1m_tau_pitch_before_blend"].append',
            'telemetry["apcr1m_tau_pitch_after_blend"].append',
            'telemetry["apcr1m_startup_guard_active"].append',
            'telemetry["apcr1m_recenter_active"].append',
            'telemetry["apcr1m_pitch_safe"].append',
            'telemetry["apcr1m_height_safe"].append',
            'telemetry["apcr1m_contact_safe"].append',
            'telemetry["apcr1m_roll_safe"].append',
            'telemetry["apcr1m_pitch_rate_safe"].append',
        ]

        for append_pattern in key_apcr1m_appends:
            assert append_pattern in source, (
                f"APCR1m telemetry append pattern '{append_pattern}' not found in simulator source"
            )

    def test_apcr1m_controller_generates_diagnostics(self):
        """Test that APCR1m controller generates all expected diagnostic keys."""
        from wheeled_biped.controllers.sagittal_velocity_damped_balance_controller import (
            SagittalVelocityDampedBalanceController,
            SagittalAuthoritySchedule,
        )

        # Create controller with APCR1m profile
        schedule = SagittalAuthoritySchedule(
            profile_name="APCR1m_test",
            applies_to_variants=("low_0p300",),
            enable_active_pitch_crossing=True,
            apc_pitch_blend_enabled=True,
            apc_pitch_blend_startup_guard_steps=100,
            apc_pitch_blend_scale_deep=0.0,
            apc_pitch_blend_scale_mid=0.25,
            apc_pitch_blend_scale_soft=0.5,
            apc_pitch_blend_scale_near=1.0,
        )

        controller = SagittalVelocityDampedBalanceController(
            authority_schedule=schedule,
        )

        # Call compute with deep error to trigger RECENTER
        tau, diagnostics = controller.compute(
            pitch_x_rad=0.05,
            pitch_rate_x_rad_s=0.0,
            sagittal_velocity_m_s=0.0,
            wheel_vel_left_rad_s=0.0,
            wheel_vel_right_rad_s=0.0,
            sagittal_position_error_m=0.15,  # Deep error to trigger RECENTER
            com_z_m=0.30,
            roll_y_rad=0.0,
            contact_valid=True,
            height_variant_name="low_0p300",
        )

        # Verify expected APCR1m diagnostic keys exist
        expected_keys = [
            "apcr1m_pitch_blend_active",
            "apcr1m_pitch_blend_scale",
            "apcr1m_pitch_blend_block_reason",
            "apcr1m_tau_pitch_before_blend",
            "apcr1m_tau_pitch_after_blend",
            "apcr1m_startup_guard_active",
            "apcr1m_recenter_active",
            "apcr1m_pitch_safe",
            "apcr1m_height_safe",
            "apcr1m_contact_safe",
        ]

        for key in expected_keys:
            assert key in diagnostics, f"Expected APCR1m diagnostic key '{key}' not found"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
