"""Analyze the combined Step D metrics CSV and produce a gate-evaluation summary.

Reads `outputs/step_d_all/step_d_all_metrics.csv` (generated by
run_step_d_all.py), evaluates safety per case/profile using the same
safety_ok logic as run_outer_loop_step_d_push.py, and produces:

  * outputs/step_d_all/step_d_summary.json — gate metrics + classification
  * docs/validation/physics_ff_low_band_support_v2_step_d_and_promotion_report.md
    — per-case tables and gate summary
"""
import argparse
import csv
import json
import pathlib
import sys

# Reuse safety helpers and case definitions from the original runner.
# Both scripts live under scripts/ so a relative import works at runtime.
try:
    from run_outer_loop_step_d_push import (  # type: ignore[import-untyped]
        MUST_NOT_FALL,
        PUSH_CASES,
        fmt as runner_fmt,
        safety_ok,
    )
except ImportError:
    # Fallback for test environments where the sibling import may fail.
    # Define the bare minimum needed locally.
    MUST_NOT_FALL = frozenset()
    PUSH_CASES = []

    def safety_ok(m):
        if m is None:
            return False, "missing"
        if m.get("fell", False):
            return False, f"fall({m.get('term_reason', '?')[:20]})"
        if m.get("hip_yaw_abs_max_rad", 0) > 0.35:
            return False, "hip_yaw_unsafe"
        if m.get("pitch_max_abs_deg", 0) > 16.0:
            return False, "pitch_unsafe"
        if m.get("roll_rms_deg", 0) > 3.0:
            return False, "roll_unsafe"
        if m.get("wbc_authority_rows", 0) > 0:
            return False, "wbc_active"
        if m.get("wbc_owner_rows", 0) > 0:
            return False, "wbc_owner_detected"
        if m.get("hidden_torque_max", 0) > 0.5:
            return False, "hidden_torque"
        if m.get("ownership_violation_max", 0) > 0:
            return False, "ownership_violation"
        return True, "safe"

    def runner_fmt(m):
        if m is None:
            return "MISSING"
        fall = f"FALL({m.get('term_reason', '?')[:12]})" if m.get("fell") else "ok"
        return (
            f"{fall} pos%={m.get('pos_pct', 0):.1f} max={m.get('max_abs', 0):.3f} "
            f"P2P={m.get('p2p', 0):.3f} out25={m.get('out25_pct', 0):.1f}% "
            f"hy={m.get('hip_yaw_abs_max_rad', 0):.3f}"
        )


ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_METRICS_CSV = ROOT / "outputs" / "step_d_all" / "step_d_all_metrics.csv"
DEFAULT_OUTPUT_JSON = ROOT / "outputs" / "step_d_all" / "step_d_summary.json"
DEFAULT_OUTPUT_REPORT = (
    ROOT
    / "docs"
    / "validation"
    / "physics_ff_low_band_support_v2_step_d_and_promotion_report.md"
)

# Constants matching run_step_d_all.py
BASE_PROFILE_LABEL = "A"
CANDIDATE_PROFILE_LABEL = "C"  # low-band v2
LOW_BAND_PROFILE_NAME = "physics_equilibrium_feedforward_outer_loop_low_band_support_v2"


# ---------------------------------------------------------------------------
# CSV → typed metrics dict
# ---------------------------------------------------------------------------

def _safe_float(v, default=0.0):
    if v in (None, "", "nan", "None", "NaN"):
        return default
    try:
        return float(v)
    except (ValueError, TypeError):
        return default


def _safe_int(v, default=0):
    if v in (None, "", "nan", "None", "NaN"):
        return default
    try:
        return int(float(v))
    except (ValueError, TypeError):
        return default


def _safe_bool(v, default=False):
    if v in (None, ""):
        return default
    return str(v).strip().lower() in ("true", "1", "1.0")


def row_to_metrics(row: dict) -> dict | None:
    """Convert a CSV row dict (all strings) into a typed metrics dict.

    Returns None if the row is missing the ``fell`` key (i.e. it is a
    metadata-only row without metric columns).
    """
    if "fell" not in row or row.get("fell", "") == "":
        return None
    return {
        "fell": _safe_bool(row.get("fell")),
        "term_reason": str(row.get("term_reason", "")),
        "min_drift": _safe_float(row.get("min_drift")),
        "max_drift": _safe_float(row.get("max_drift")),
        "max_abs": _safe_float(row.get("max_abs")),
        "p2p": _safe_float(row.get("p2p")),
        "pos_pct": _safe_float(row.get("pos_pct")),
        "neg_pct": _safe_float(row.get("neg_pct")),
        "zero_crossings": _safe_int(row.get("zero_crossings")),
        "out15_pct": _safe_float(row.get("out15_pct")),
        "out25_pct": _safe_float(row.get("out25_pct")),
        "pitch_max_abs_deg": _safe_float(row.get("pitch_max_abs_deg")),
        "roll_rms_deg": _safe_float(row.get("roll_rms_deg")),
        "hip_yaw_abs_max_rad": _safe_float(row.get("hip_yaw_abs_max_rad")),
        "yaw_drift_max_rad": _safe_float(row.get("yaw_drift_max_rad")),
        "wbc_authority_rows": _safe_int(row.get("wbc_authority_rows")),
        "wbc_owner_rows": _safe_int(row.get("wbc_owner_rows")),
        "hidden_torque_max": _safe_float(row.get("hidden_torque_max")),
        "ownership_violation_max": _safe_float(row.get("ownership_violation_max")),
        "steps": _safe_int(row.get("steps")),
    }


# ---------------------------------------------------------------------------
# CSV loading and grouping
# ---------------------------------------------------------------------------

def load_metrics(path: pathlib.Path) -> list[dict]:
    """Load the combined CSV and return rows as raw dicts."""
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def group_rows(
    raw_rows: list[dict],
) -> dict[tuple[str, str], dict | None]:
    """Group raw CSV rows by ``(case_id, profile)`` → typed metrics dict.

    Returns a flat dict keyed by ``(case_id, profile_label)``.  When the
    row lacks metric columns (sim failed), the value is ``None``.
    """
    groups: dict[tuple[str, str], dict | None] = {}
    for row in raw_rows:
        case = str(row.get("case_id", "")).strip()
        prof = str(row.get("profile", "")).strip()
        if not case or not prof:
            continue
        m = row_to_metrics(row)
        groups[(case, prof)] = m
    return groups


# ---------------------------------------------------------------------------
# Gate evaluation
# ---------------------------------------------------------------------------

def compute_gates(
    groups: dict[tuple[str, str], dict | None],
) -> dict:
    """Evaluate safety gates by comparing candidate (C) vs baseline (A).

    Returns a dict with keys:
      must_not_fall_pass, any_hard_fail, max_drift_C, c_not_worse_count,
      total_cases
    """
    must_not_fall_pass = True
    any_hard_fail = False
    max_drift_C = 0.0
    c_not_worse_count = 0
    total_cases = 0
    # Use the union of PUSH_CASES and case IDs that actually appear in the
    # data so the test harness can work with a partial CSV.
    data_case_ids = {k[0] for k in groups}
    case_ids = sorted(data_case_ids | {c[0] for c in PUSH_CASES})

    for case_id in case_ids:
        a = groups.get((case_id, BASE_PROFILE_LABEL))
        c = groups.get((case_id, CANDIDATE_PROFILE_LABEL))
        if a is None and c is None:
            continue  # skip cases where neither profile has data
        total_cases += 1
        sok_c, _ = safety_ok(c)
        if not sok_c:
            any_hard_fail = True
            if case_id in MUST_NOT_FALL and c and c.get("fell", False):
                must_not_fall_pass = False
        if c:
            max_drift_C = max(max_drift_C, c.get("max_abs", 0.0))
        # C not worse: max_abs C <= max_abs A + 0.05 m and falls not worse
        c_not_worse = (
            c is not None
            and a is not None
            and c.get("max_abs", 0.0) <= a.get("max_abs", 0.0) + 0.05
            and (not c.get("fell", False) or a.get("fell", False))
        )
        if c_not_worse:
            c_not_worse_count += 1

    return {
        "must_not_fall_pass": must_not_fall_pass,
        "any_hard_fail": any_hard_fail,
        "max_drift_C": max_drift_C,
        "c_not_worse_count": c_not_worse_count,
        "total_cases": total_cases,
    }


def classify(gates: dict) -> str:
    """Determine the Step D classification from gate metrics."""
    if not gates["must_not_fall_pass"]:
        return "STEP_D_RANDOM_PUSH_FAIL"
    if gates["any_hard_fail"] and gates["c_not_worse_count"] < gates["total_cases"] // 2:
        return "STEP_D_RANDOM_PUSH_FAIL"
    if gates["any_hard_fail"]:
        return "STEP_D_RANDOM_PUSH_PASS_WITH_MONITORING"
    if gates["c_not_worse_count"] >= gates["total_cases"] - 1:
        return "STEP_D_RANDOM_PUSH_PASS"
    if gates["c_not_worse_count"] >= gates["total_cases"] // 2:
        return "STEP_D_RANDOM_PUSH_PASS_WITH_MONITORING"
    return "STEP_D_RANDOM_PUSH_INCONCLUSIVE"


# ---------------------------------------------------------------------------
# Report generation
# ---------------------------------------------------------------------------

def generate_report(
    groups: dict[tuple[str, str], dict | None],
    gates: dict,
    classification: str,
) -> str:
    """Build the markdown report text."""
    lines = [
        "# Step D: Random Push Disturbance Validation + Promotion Report",
        "",
        "**Profiles:**",
        f"* **A (baseline):** `height_scheduled_pitch_equilibrium_trim`",
        f"* **C (candidate):** `{LOW_BAND_PROFILE_NAME}`",
        f"",
        f"**Classification:** `{classification}`",
        "",
        "---",
        "",
        "## Per-Case Results",
        "",
    ]

    # Build a table per profile
    for profile_label, profile_title in [
        ("A", "Baseline (A)"),
        ("C", "Low-Band v2 Candidate (C)"),
    ]:
        lines.append(f"### {profile_title}")
        lines.append("")
        lines.append(
            "| Case | Height | Push(N) | Fell | max_abs | P2P | out25% | hip_yaw | safe |"
        )
        lines.append(
            "|------|--------|---------|------|---------|-----|--------|---------|------|"
        )
        # Collect unique case IDs
        case_ids = sorted({k[0] for k in groups})
        for case_id in case_ids:
            m = groups.get((case_id, profile_label))
            if m is None:
                lines.append(
                    f"| {case_id} | — | — | — | — | — | — | — | NO DATA |"
                )
                continue
            sok, _ = safety_ok(m)
            lines.append(
                f"| {case_id} | — | — | "
                f"{'FALL' if m.get('fell') else 'ok'} | "
                f"{m.get('max_abs', 0):.3f} | "
                f"{m.get('p2p', 0):.3f} | "
                f"{m.get('out25_pct', 0):.1f} | "
                f"{m.get('hip_yaw_abs_max_rad', 0):.3f} | "
                f"{sok} |"
            )
        lines.append("")

    # Gate summary
    lines.extend([
        "## Gate Summary",
        "",
        f"| Gate | Value |",
        f"|------|-------|",
        f"| must_not_fall_pass (C) | {gates['must_not_fall_pass']} |",
        f"| any_hard_fail (C) | {gates['any_hard_fail']} |",
        f"| max_drift_C (m) | {gates['max_drift_C']:.3f} |",
        f"| c_not_worse_count | {gates['c_not_worse_count']} / {gates['total_cases']} |",
        f"| total_cases | {gates['total_cases']} |",
        "",
        "## Decision",
        "",
        f"- **{classification}**",
        "",
    ])

    if classification == "STEP_D_RANDOM_PUSH_PASS":
        lines.extend([
            "- Profile C passed all push disturbance gates.",
            "- C is not worse than A in drift or falls across all tested cases.",
            "- No hard safety failures, no MUST_NOT_FALL violations.",
            "- **Recommendation:** Promote low-band v2 as the new default.",
        ])
    elif classification == "STEP_D_RANDOM_PUSH_PASS_WITH_MONITORING":
        lines.extend([
            "- Profile C passed the MUST_NOT_FALL gate but had some safety flags or borderline drift.",
            "- **Recommendation:** Promote with monitoring — re-evaluate after broader testing.",
        ])
    elif classification == "STEP_D_RANDOM_PUSH_FAIL":
        lines.extend([
            "- Profile C failed a MUST_NOT_FALL case or was substantially worse than A.",
            "- **Recommendation:** Do not promote; investigate and tune before re-evaluating.",
        ])
    else:  # INCONCLUSIVE
        lines.extend([
            "- Insufficient data to reach a firm conclusion.",
            "- **Recommendation:** Re-run with more cases or check for missing data.",
        ])

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Analyze Step D push-disturbance metrics CSV and produce gate evaluation."
    )
    parser.add_argument(
        "--metrics-csv",
        type=pathlib.Path,
        default=DEFAULT_METRICS_CSV,
        help=f"Path to combined metrics CSV (default: {DEFAULT_METRICS_CSV})",
    )
    parser.add_argument(
        "--output-json",
        type=pathlib.Path,
        default=DEFAULT_OUTPUT_JSON,
        help=f"Path for JSON summary (default: {DEFAULT_OUTPUT_JSON})",
    )
    parser.add_argument(
        "--output-report",
        type=pathlib.Path,
        default=DEFAULT_OUTPUT_REPORT,
        help=f"Path for markdown report (default: {DEFAULT_OUTPUT_REPORT})",
    )
    return parser.parse_args(argv)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)

    metrics_csv = pathlib.Path(args.metrics_csv)
    if not metrics_csv.is_file():
        print(f"ERROR: metrics CSV not found: {metrics_csv}", file=sys.stderr)
        sys.exit(1)

    raw_rows = load_metrics(metrics_csv)
    if not raw_rows:
        print(f"ERROR: metrics CSV is empty: {metrics_csv}", file=sys.stderr)
        sys.exit(1)

    groups = group_rows(raw_rows)
    gates = compute_gates(groups)
    classification = classify(gates)

    # Write JSON summary
    out_json = pathlib.Path(args.output_json)
    out_json.parent.mkdir(parents=True, exist_ok=True)
    summary = {
        "classification": classification,
        "must_not_fall_pass": gates["must_not_fall_pass"],
        "any_hard_fail": gates["any_hard_fail"],
        "max_drift_C": round(gates["max_drift_C"], 4),
        "c_not_worse_count": gates["c_not_worse_count"],
        "total_cases": gates["total_cases"],
    }
    out_json.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(f"JSON summary written to {out_json}", flush=True)
    print(f"  Classification: {classification}", flush=True)

    # Write markdown report
    report = generate_report(groups, gates, classification)
    out_report = pathlib.Path(args.output_report)
    out_report.parent.mkdir(parents=True, exist_ok=True)
    out_report.write_text(report, encoding="utf-8")
    print(f"Report written to {out_report}", flush=True)


if __name__ == "__main__":
    main()
